spring.application.name=spring-boot-whkc
server.port=20118
spring.datasource.url=jdbc:sqlserver://192.168.18.232:6423;Databasename=zbpf7
spring.datasource.username=zb
spring.datasource.password=Zbpf@2008!@#qwe
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.rabbitmq.host=47.111.168.88
spring.rabbitmq.port=5672
spring.rabbitmq.username=hbrd
spring.rabbitmq.password=hbrd20190918





