spring.application.name=spring-boot-whkc

spring.rabbitmq.host=47.111.168.88
spring.rabbitmq.port=5672
spring.rabbitmq.username=hbrd
spring.rabbitmq.password=hbrd20190918

server.port=8105

spring.datasource.url=jdbc:oracle:thin:@//192.168.0.115:1521/orclpdb
spring.datasource.username=dherp
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.max-wait=300000
